name: Update README with File Counts

on:
  schedule:
    # cron 문법을 사용하며, UTC 기준입니다.
    # 매주 월요일 00:00 UTC (한국 시간 월요일 오전 9시)에 실행되도록 변경합니다.
    - cron: '0 0 * * 1'
      
  # 수동 실행을 위해 workflow_dispatch는 남겨두는 것이 좋습니다.
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Seoul'
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run file count script
        run: python count_files.py

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Docs: Update README with file counts"
          git push
